name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: docker://kivy/buildozer:latest
      with:
        entrypoint: /bin/bash
        # هنا بنجبر السيرفر يوافق على رخص الـ SDK أوتوماتيك قبل البناء
        args: -c "mkdir -p ~/.android && touch ~/.android/repositories.cfg && yes | buildozer -v android debug"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ./.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/*/bin/*.apk
