name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build with Buildozer Docker
      uses: docker://kivy/buildozer:latest
      options: --user root
      with:
        # هنا بنجبر السيرفر يجاوب بـ yes تلقائياً على أي سؤال من الـ buildozer
        args: sh -c "yes | buildozer -v android debug"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ./.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/*/bin/*.apk
